### ISSUE TITLE
DivideByZero error

### ISSUE THREAD

**Issue by Hjel2** [Automatic-Entrepreneur/Automatic-Entrepreneur.github.io#3]
Some companies can call DivideByZero errors in performance_summary -- IE "AVOS & CO LIMITED"
Resolve this by using linear regression (sklearn.linear_model.LinearRegression)

**Comment by Joseph-Rance** [comment]
Was this fixed in 9df2ab479788842127a1385082f5ca8e279976f7 ?

**Comment by Hjel2** [comment]
Yes, that issue is gone!
However, it's highlighted a new one... "value remained steady sharply at 0.0 GBP."
